{
 "title": "Webapp test",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Webapp pod running status",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "group(kube_pod_container_status_running) by (pod,namespace)",
     "legendFormat": "{{namespace}} // {{pod}} "
    }
   ]
  },
  {
   "title": "Webapp pod restarts status",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  rate(kube_pod_container_status_restarts_total[10m])\n)",
     "legendFormat": "{{namespace}} / {{pod}} "
    }
   ]
  },
  {
   "title": "Webapp pod total restarts count",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(kube_pod_container_status_restarts_total[30m]))*1000",
     "legendFormat": "{{namespace}} / {{pod}} "
    }
   ]
  }
 ]
}